bitrise-io/bitrise-webhooks

- README.md
Added entry for environment variables support in slack :)
> Added contributor entry

- bitriseapi/bitriseapi.go
- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/common/common.go
- service/hook/github/github.go
- service/hook/github/github_test.go
GH Pull Request changes to expose source, destination branch with the merge branch
> github pr support changes

- README.md
- bitriseapi/bitriseapi.go
- service/hook/common/common.go
- service/hook/common/default_response_provider.go
- service/hook/default_response_provider.go
- service/hook/endpoint.go
- service/hook/endpoint_test.go
- service/hook/slack/slack.go
Finishing touches before release to hooks.bitrise.io
> Skip CI - finishing touches

- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/bitbucketv2/bitbucketv2_test.go
Generic PR support with the following providers:
* GitHub
* Bitbucket Server & Cloud
> Pull Request support enhancements

- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/bitbucketv2/bitbucketv2_test.go
- service/hook/github/github.go
- service/hook/github/github_test.go
> minor PR skip text change

- bitriseapi/bitriseapi.go
- bitriseapi/bitriseapi_test.go
- service/hook/github/github.go
- service/hook/github/github_test.go
GitHub tag push event handling
> generalize Push Event (previously Code Push)

- README.md
- bitrise.yml
no need to e.g. godep go install anymore, go install works just fine
updated bitrise.yml and README
> bit of godep cleanup now that we use vendor

- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/bitbucketv2/bitbucketv2_test.go
Bitbucket Tag push event handling
changed method names etc. to reflect that it's now a generic "push" event handler, which can …
> BitBucket tag event handling

- README.md
- bitriseapi/bitriseapi.go
- service/hook/github/github.go
- service/hook/github/github_test.go
- service/hook/gitlab/gitlab.go
- service/hook/gitlab/gitlab_test.go
Adds support for GitLab Merge Requests
> gitlab pr support

- README.md
- service/hook/gitlab/gitlab.go
- service/hook/gitlab/gitlab_test.go
gitlab tag push event handling
> gitlab tag push event handling - DONE

- Godeps/Godeps.json
- vendor/github.com/bitrise-io/go-utils/builtinutil/builtinutil.go
- vendor/github.com/bitrise-io/go-utils/sliceutil/sliceutil.go
> deps update

- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/visualstudioteamservices/visualstudioteamservices.go
- service/hook/visualstudioteamservices/visualstudioteamservices_test.go
> golint fixes

- README.md
- service/hook/deveo/deveo.go
- service/hook/deveo/deveo_test.go
- service/hook/endpoint.go
This pull request implements support for Deveo - yet another code hosting and collaboration platform.
This Pull Request makes …
> Deveo support

- service/hook/endpoint.go
> minor "normalization"

- Godeps/Godeps.json
- vendor/github.com/davecgh/go-spew/LICENSE
- vendor/github.com/davecgh/go-spew/spew/bypass.go
- vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
- vendor/github.com/davecgh/go-spew/spew/common.go
- vendor/github.com/davecgh/go-spew/spew/config.go
- vendor/github.com/davecgh/go-spew/spew/doc.go
- vendor/github.com/davecgh/go-spew/spew/dump.go
- vendor/github.com/davecgh/go-spew/spew/format.go
- vendor/github.com/davecgh/go-spew/spew/spew.go
- vendor/github.com/stretchr/testify/assert/assertions.go
> godeps update

- README.md
Forgot to add Deveo to the list on the top.
memory consumption by …
> Add Deveo to supported webhooks / providers.

- bitrise.yml
normalized by the workflow-editor
moved previous comments into description properties
> normalized an updated bitrise.yml

- bitriseapi/bitriseapi.go
> Added triggered by type to TriggerAPIParamsModel

- Godeps/Godeps.json
- README.md
- bitriseapi/bitriseapi.go
- service/hook/assembla/assembla_test.go
- service/hook/endpoint.go
- service/hook/passthrough/passthrough.go
- service/hook/passthrough/passthrough_test.go
- vendor/github.com/bitrise-io/go-utils/colorstring/colorstring.go
- vendor/github.com/gorilla/mux/README.md
Pass-through hook endpoint / handler: a service independent simple transformer which just reads and passes the Headers and the …
> passthrough hook handler & some minor debugging revisions

- bitriseapi/bitriseapi.go
- service/hook/common/default_response_provider.go
Do not respond with error if build was not triggered because of a known reason (e.g. no matching triggers).
Display an error in …
>  Respond with 200 if build was not triggered of known reason

- README.md
Re: https://github.com/bitrise-io/bitrise-webhooks/issues/69#issuecomment-357063419
> README: added note about how to run the tests

- bitriseapi/bitriseapi.go
- service/hook/github/github.go
- service/hook/github/github_test.go
Adds more information about pull request (diff URL) and push events (commit modification paths) for website
> Add diff URL and push modification paths to transformed response

- service/hook/passthrough/passthrough.go
- service/hook/passthrough/passthrough_test.go
> Increase passthrough body size from ~10KB to ~20KB

- README.md
> Link to How to add new provider section in Readme

- README.md
Update build status icon in readme
> Update build status icon in readme

- README.md
Update contributors section in README.md
PR: #91
> Update contributors section in README.md

- service/hook/bitbucketserver/bitbucketserver.go
- service/hook/bitbucketserver/bitbucketserver_test.go
- [X ] Run `go fmt` on your files (e.g. `go fmt ./service/common.go`, or on the whole `service` folder: `go fmt ./service/...`)
- [X ] Write tests for your code
- [ N/A] If your Pull Request is more than a bug fix you should also check `README.md` and change/add the descriptions there - also
feel free to …
> Added support for PR modification webhook on bitbucket server

- service/hook/bitbucketserver/bitbucketserver.go
- service/hook/bitbucketserver/bitbucketserver_test.go
Do not throw an exception on MERGED webhook event status. In this case, we have to skip the build triggering. A next webhook …
> Do not throw exception on MERGED webhook event status [WEB-3998]

- bitrise.yml
- version/version.go
Move the release flow into bitrise yml file because of version management
> Move the release flow into bitrise yml file

- bitriseapi/bitriseapi.go
- service/hook/bitbucketserver/bitbucketserver_test.go
- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/bitbucketv2/bitbucketv2_test.go
- service/hook/common/default_response_provider.go
- service/hook/github/github.go
- service/hook/github/github_test.go
- service/hook/gitlab/gitlab.go
- service/hook/gitlab/gitlab_test.go
This PR is the part of [Introduce Origin Repository variable to incoming …
> Add HeadRepositoryURL and BaseRepositoryURL to BuildParamsModel

- metrics/common.go
We are getting a lot of H18 errors. Insert a panic checker function to get more information about the error.
> Investigate H18 errors

- bitriseapi/bitriseapi.go
- bitriseapi/bitriseapi_test.go
- service/hook/assembla/assembla.go
- service/hook/assembla/assembla_test.go
- service/hook/bitbucketserver/bitbucketserver.go
- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/bitbucketv2/bitbucketv2_test.go
- service/hook/common/common.go
- service/hook/deveo/deveo.go
- service/hook/endpoint.go
- service/hook/github/github.go
- service/hook/github/github_test.go
- service/hook/gitlab/gitlab.go
- service/hook/gitlab/gitlab_test.go
- service/hook/gogs/gogs.go
- service/hook/passthrough/passthrough.go
- service/hook/slack/slack.go
- service/hook/visualstudioteamservices/visualstudioteamservices.go
Updating triggerBuild with custom TriggeredBy field values for GitHub, GitLab and BitBucket V2/Cloud.
> Bins 505 update providers

- README.md
- service/hook/visualstudioteamservices/visualstudioteamservices.go
- service/hook/visualstudioteamservices/visualstudioteamservices_test.go
Fixes #80 :) 
Typical dev flow (creating feature branch -> updating feature branch -> creating PR -> updating feature branch -> …
> Add support for Azure DevOps pull request events

- bitrise.yml
- service/hook/bitbucketserver/bitbucketserver.go
- service/hook/bitbucketserver/bitbucketserver_test.go
Update to contains triggered_by info
memory consumption by 99%, as …
> Update bitbucket server webhook handler

- README.md
GitLab does store webhook event history & shows their details on its UI. This PR updates our README.md accordingly.
> Update GitLab hook processing details in README.md

- Dockerfile.internal-platform
- deployments/helm/values.ci.yaml
> feat: TIP-1141 add Dockerfile and deployment template for IP

- bitriseapi/bitriseapi.go
- service/hook/github/github.go
- service/hook/github/github_test.go
Reverts bitrise-io/bitrise-webhooks#128
Causing issue:
https://bitrise.app.opsgenie.com/incident/detail/9a55f2c1-041a-407b-9927-573c60313c4a
> Revert "Forward unverified merge ref in a new field"

- bitriseapi/bitriseapi.go
- service/hook/github/github.go
- service/hook/github/github_test.go
Reverts bitrise-io/bitrise-webhooks#129
Original PR has all the context: https://github.com/bitrise-io/bitrise-webhooks/pull/128
> Forward unverified merge ref in a new field - take 2

- service/hook/gitlab/gitlab.go
- service/hook/gitlab/gitlab_test.go
Potential fix for https://bitrise.atlassian.net/browse/SSW-127
> [SSW-127] Fix failing webhooks for Gitlab squashed merge requests

- service/hook/common/skipci.go
- service/hook/common/skipci_test.go
> Handle skip ci flag in markdown [SSW-526]

- service/hook/common/skipci.go
- service/hook/common/skipci_test.go
> Handle escaped skip ci flag in markdown [SSW-526]

- catalog-info.yaml
> chore: Set owner to bitrise-webdevs

- service/hook/common/metrics.go
- service/hook/github/metrics.go
> [BIVS-2103] Patch: add latest_commit_timestamp

- service/hook/common/metrics.go
- service/hook/github/metrics.go
- service/hook/github/metrics_test.go
This PR adds new properties to metrics:
- all metrics:  `provider_type` and `repository`
- PullRequestMetrics: …
> Related prs

- go.mod
- go.sum
- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/bitbucketv2/metrics.go
- service/hook/bitbucketv2/metrics_test.go
- service/hook/common/metrics.go
- service/hook/endpoint.go
- service/hook/github/metrics.go
- service/hook/gitlab/metrics.go
- vendor/github.com/go-playground/webhooks/v6/LICENSE
- vendor/github.com/go-playground/webhooks/v6/bitbucket/bitbucket.go
- vendor/github.com/go-playground/webhooks/v6/bitbucket/payload.go
- vendor/modules.txt
This PR adds git event tracking for BitBucket webhooks.
Because BitBucket `repo:push` webhooks may contain information about …
> Bivs 2103 bitbucket metrics

- bitrise.yml
- bitriseapi/bitriseapi.go
- metrics/common.go
- service/common.go
- service/hook/endpoint.go
> Change logging format

- bitrise.yml
- bitriseapi/bitriseapi.go
- metrics/common.go
- service/common.go
- service/hook/endpoint.go
- service/hook/github/metrics.go
This was in the original implementation:
> Removed unused syncs and updated github payload signature check

- bitriseapi/bitriseapi.go
- bitriseapi/bitriseapi_test.go
- internal/pubsub/pubsub.go
- service/hook/bitbucketv2/bitbucketv2.go
- service/hook/bitbucketv2/bitbucketv2_test.go
- service/hook/endpoint.go
- service/hook/github/github.go
- service/hook/github/github_test.go
- service/hook/gitlab/gitlab.go
- service/hook/gitlab/gitlab_test.go
BitBucket Cloud, GitHub and GitLab for now
> [BIVS-2513] Use PR comment hooks

- bitrise.yml
using asdf requires to execute go reshim before running errcheck …
> Add Bitrise Ubuntu 22.04 stack image with asdf support

- Dockerfile.internal-platform
- bitrise.yml
- bitriseapi/bitriseapi.go
- bitriseapi/bitriseapi_test.go
- config/config.go
- main.go
- service/hook/endpoint.go
Added LOG_ONLY_MODE and BUILD_TRIGGER_URL as config options instead of hardcoded values/logic.
> [WEB-4618] more config options

- service/hook/common/skipci.go
- service/hook/common/skipci_test.go
> added bitrise skip

- routes.go
Add support for dropping traces when the specified header is set.
Tested on staging.
> [BACKEND-478]
