README.md
bitriseapi/bitriseapi.go
service/hook/gogs/gogs_test.go
service/hook/slack/slack.go
service/hook/slack/slack_test.go

Hi! I needed this feature: https://bitrise.uservoice.com/forums/235233-general/suggestions/14200494-allow-for-custom-params-for-slack-command-to-be-se
On the chatrooms you guys gave me the option to use the API directly with the advanced build feature, thanks! I take a stab at how I would see this working, sorry I'm awful at Golang! Never had used it before and couldn't make the server run locally to test it working. Please if anyone can review this and make it better...
The usage would be:
Slack command calls `/bitrise branch:develop|env[DEVICE_NAME]:iPhone de Rafael|env[DEVICE_UDID]:8237842783478237878234`
webhook-processor outputs
`"build_params":{"branch":"develop","environments":[{"mapped_to":"DEVICE_NAME","value":"iPhone de …

Add support for Environment Variables in Slack commands.

---

bitriseapi/bitriseapi.go
service/hook/common/common.go
service/hook/default_response_provider.go
service/hook/endpoint.go

My first lines of Go code so apologies if it is totally out of place :)
I was trying to implement this in the common code as suggested here: https://github.com/bitrise-io/bitrise-webhooks/issues/2 but couldn't realize how to access the commit message from there so decided to put in the TransformRequest instead which seemed like good place because it already has ShouldSkip.
Would like to hear if this is good way to do it or if it should be placed somewhere else? 
Also this only implements it for the github push event so would need to implement it other places also where needed...

Experimental skip-ci support for github

---

README.md

Looks like Github has renamed it.

Update menu item name for GitHub instructions

---

app.json
service/hook/bitbucketv2/bitbucketv2.go
service/hook/bitbucketv2/bitbucketv2_test.go

As documented in [here](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html) mercurial repositories have `named_branch` instead of `branch` typeoin bitrise webhooks.
- type: The type of reference with the change. 
- branch, or tag for Git repositories.
- named_branch, bookmark or tag for Mercurial repositories.
This PR enable wehbhooks to work with mercurial repositories.

Bitbucket mercurial support

---

README.md
service/hook/bitbucketv2/bitbucketv2_test.go
service/hook/common/common.go
service/hook/common/default_response_provider.go
service/hook/deveo/deveo_test.go
service/hook/endpoint.go
service/hook/github/github_test.go
service/hook/gitlab/gitlab.go
service/hook/gitlab/gitlab_test.go
service/hook/gogs/gogs_test.go
service/hook/slack/slack_test.go
service/hook/visualstudioteamservices/visualstudioteamservices_test.go

DontWaitForTriggerResponse if true the Trigger API request will be sent,
but the handler won't wait for the response from the Trigger API,
it'll respond immediately after calling the Trigger API

DontWaitForTriggerResponse option added - return a response for GitLab as fast as possible

---

Gopkg.toml
bitrise.yml
heroku-vendor.json
vendor/vendor.json

Heroku now supports Go packages with dep as dependency tool, out of box,
if you declare the heroku metadata in Gopkg.toml.
Old method doesnt even work anymore, so this was a no-brainer :P

migration to new Gopkg.toml based Heroku def

---

service/hook/bitbucketv2/bitbucketv2.go
service/hook/bitbucketv2/bitbucketv2_test.go

I read issue #65 which suggests a small fix to support Bitbucket Server (which I need too), I had 15 minutes to spare so I …

Bitbucket v2: return default value when X-Attempt-Number header is missing

---

service/hook/bitbucketserver/bitbucketserver.go
service/hook/bitbucketserver/bitbucketserver_test.go

This pull request fixes a bug causing newly pushed branches on a Bitbucket Server repository not to trigger a build in Bitrise. See issue #69.
Fixes #69

Add support for new branch triggers from Bitbucket Server

---

service/hook/gitlab/gitlab.go
service/hook/gitlab/gitlab_test.go

Today, the GitLab webhook doesn't take into account the ["`action`" …

GitLab: adds more intuitive merge request event filtering

---

bitriseapi/bitriseapi.go
service/hook/bitbucketv2/bitbucketv2.go
service/hook/bitbucketv2/bitbucketv2_test.go
service/hook/github/github.go
service/hook/github/github_test.go
service/hook/gitlab/gitlab.go
service/hook/gitlab/gitlab_test.go

Consume Author name for GitHub, GitLab and Bitbucker hooks

Add PR/MR author info

---

README.md
service/hook/gogs/gogs.go
service/hook/gogs/gogs_test.go

This PR (continues #43) addresses #30 with two changes:
Adds support for Tag triggers, which are sent as ref_type: "tag", ref: "TAGNAME".
Adds doc references to Gitea, which the GOGS handler is compatible with (since Gitea is a GOGS fork).
Includes @mac89 and @crrobinson14 's commits from #91 
We really wanted to merge the PR and we had some suggestions. Thank you guys the contribution and feel free to pick another issue as well 😺

Merge: Add support for tag Webhook triggers in Gogs/Gitea #91

---

service/hook/bitbucketserver/bitbucketserver.go
service/hook/bitbucketserver/bitbucketserver_test.go

- [X ] Run `go fmt` on your files (e.g. `go fmt ./service/common.go`, or on the whole `service` folder: `go fmt ./service/...`)
- [X ] Write tests for your code
- [X ] If your Pull Request is more than a bug fix you should also check `README.md` and change/add the descriptions there - also
feel free to add …

Added support for pr:from_ref_updated hook on bitbucket server

---

service/hook/github/github.go
service/hook/github/github_test.go

Check the draft state of the PR and set the GITHUB_PR_IS_DRAFT in the CI. Customers can check the env. var. value and can create a custom abort logic on it. 
This is the early stage of the draft aborting feature.

[PLANG-310] Set GITHUB_PR_IS_DRAFT env var for draft PRs (GitHub)

---

service/hook/bitbucketv2/bitbucketv2.go
service/hook/common/common.go
service/hook/endpoint.go
service/hook/github/github.go
service/hook/gitlab/gitlab.go

Logging how many users use ci skip in pull request and merge request descriptions.

Logging skipped by pr description

---

service/hook/github/github.go
service/hook/github/github_test.go

This Pull Request adds support for an extra [Github Pull Request trigger](https://docs.github.com/en/actions/using-workflows/eve …

[GitHub] Add support for ready_for_review github trigger

---

service/hook/github/github.go
service/hook/github/github_test.go

This reverts commit 84975a4290e457f7ee82238f16c8990bc80a2a35.
This Pull Request reverts #118 . We started to get reports from …

Revert "Add support for ready_for_review github trigger (#118)"

---

catalog-info.yaml

Hello! This is your `catalog-info.yaml` file that registers your service with Backstage.
Please merge this PR and Backstage will pick it up from there.
*- Generated by Backstage*

Register service bitrise-webhooks in Backstage

---

bitriseapi/bitriseapi.go
service/hook/github/github.go
service/hook/github/github_test.go

Follow-up to #125 with a more permanent solution for always checking out the correct merge ref.
This PR forwards the merge ref …

Forward unverified merge ref in a new field

---

service/hook/gitlab/gitlab.go
service/hook/gitlab/gitlab_test.go

Similar to https://github.com/bitrise-io/bitrise-webhooks/pull/125, which checks the merge ref in GitHub webhooks, this PR does …

Forward GitLab merge ref only if it's up-to-date

---

go.mod
go.sum
service/hook/bitbucketv2/bitbucketv2.go
service/hook/bitbucketv2/metrics.go
service/hook/bitbucketv2/metrics_test.go
service/hook/common/metrics.go
service/hook/endpoint.go
service/hook/github/metrics.go
service/hook/github/metrics_test.go
service/hook/gitlab/metrics.go
service/hook/gitlab/metrics_test.go
vendor/github.com/go-playground/webhooks/v6/LICENSE
vendor/github.com/go-playground/webhooks/v6/bitbucket/bitbucket.go
vendor/github.com/go-playground/webhooks/v6/bitbucket/payload.go
vendor/modules.txt

This PR [reintroduces Bitbucket metrics](https://github.com/bitrise-io/bitrise-webhooks/pull/147), that had to be [rolled …

BIVS-2257 bitbucket metrics

---

service/hook/github/metrics.go
service/hook/github/metrics_test.go

Non-PR issue comments return `nil` as metrics, wrapped in an interface so we didn't properly check if it was `nil` until now.

[BIVS-2486] don't panic on non-PR issue comments

---

bitriseapi/bitriseapi.go
service/hook/slack/slack.go
service/hook/slack/slack_test.go

Add support for build trigger responses with multiple results.

[BIVS-2846] Accept build trigger responses with multiple results

---

service/hook/visualstudioteamservices/visualstudioteamservices.go
service/hook/visualstudioteamservices/visualstudioteamservices_test.go

Also send commit_messages field for PR merge push events [SSW-2040]

---

service/hook/gitlab/gitlab.go
service/hook/gitlab/gitlab_test.go

Creating a branch from the GitLab UI results in a push event with no commits in the payload. Instead of a 400, just skip the build with a message.

[BIVS-2946] Don't reply with 400 to an empty push from GitLab

---

service/hook/bitbucketv2/bitbucketv2.go
service/hook/common/common.go
service/hook/common/skipci.go
service/hook/common/skipci_test.go
service/hook/endpoint.go
service/hook/github/github.go
service/hook/gitlab/gitlab.go

This PR extends to support for skip instructions to PR comments (which can be used to trigger builds). This is to provide a better experience with various automated tools that create comments (review tools, AI agents etc.)

[BIVS-3372] check for skip ci in PR comments too
